ticket/protected/controllers/LayananController.php
<?php

class LayananController extends Controller
{

	public function actionIndex()
	{
		$this->layout='//layouts/column1';
		
		$data['title'] = 'Services & Facilities';
		$category = Service::model()->getCategory($this->languageID);
		// $menu = Layanan::model()->getSub($this->languageID);
		$layanan = Service::model()->getServiceAll(false, false, $this->languageID);

		$this->render('index', array(
			'data'=>$data,
			'menu'=>$category,
			'layanan'=>$layanan,
		));
	}

	// public function actionIndex()
	// {
	// 	$this->layout='//layouts/content';
	// 	$data = Page::model()->getPage('our-services', $this->languageID);
	// 	$menu = Layanan::model()->getSub($this->languageID);
	// 	$layanan = Layanan::model()->getLayanan($this->languageID);

	// 	$this->render('index', array(
	// 		'data'=>$data,
	// 		'menu'=>$menu,
	// 		'layanan'=>$layanan,
	// 	));
	// }

	public function actionView($id)
	{
		$this->layout='//layouts/column1';

		// $data = Page::model()->getPage('our-services', $this->languageID);
		$data['title'] = 'Services & Facilities';
		$category = Service::Model()->getCategory($this->languageID);

		$id = abs((int) $_GET['id']);
		$detail = Service::Model()->getData($id,$this->languageID);
		$layananAll = Service::Model()->getServiceAll(3, $id, $this->languageID);

		$this->render('view', array(
			'data'=>$data,
			'menu'=>$category,
			'detail'=>$detail,
			'listAll'=>$layananAll,
		));
	}
}

ticket/protected/views/layanan/index.php
<?php
$this->pageTitle = $data['title'].' - '.$this->pageTitle;
?>
<div class="content-inside-about prelatif">
	<div class="clear h140"></div>
	<div class="prelatif container padding-left-30">
		<div class="left breadcumb"><a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Home</a> &gt; <b>Services & Facilities</b></div>
		<div class="clear height-10"></div>
		<div class="clear"></div>
	</div>
	<div class="lines-green"></div>
	<div class="prelatif container margin-left-30">
		<div class="clear height-25"></div>

		<!-- /. start left content -->
		<div class="left w257 left-content">
			<div class="inside w232">
				<?php foreach ($menu as $key => $v_Category): ?>
				<div class="t-nws-detail text-gothic"><b><?php echo ucwords($v_Category->category); ?></b></div>
				<div class="clear height-10"></div>
				<div class="menu-left-inscontent">
					<?php $menusub = Service::Model()->getMenuByCategory(1, $v_Category->service_category_id); ?>
					<!-- <ul> -->
						<?php $this->widget('zii.widgets.CMenu', array(
							    'items'=>$menusub,
							    'encodeLabel'=>false,
							)); ?>
					<!-- </ul> -->
				</div>
				<div class="clear height-20"></div>
				<?php endforeach ?>

			</div>
			<div class="clear"></div>
		</div>
		<!-- /. End left content -->
		
		<!-- /. start right content -->
		<div class="left w842 right-content">
			<div class="text-content inside">
				<h1 class="title-toppages"><font style="font-weight: normal;">Services & Facilities from</font></h1>
				<div class="clear height-3"></div>
				<h1 class="title-toppages">Surabaya Spine Clinic</h1>
				<div class="clear height-20"></div>

				<div class="list-item-facilities-data">
					<div class="row">
								<?php $categr = ''; ?>
								<?php foreach ($layanan as $key => $value): ?>				
								<?php if ($value->category != $categr): ?>
									<div class="clear"></div>
									<div class="name_kategori text-gothic">
										<?php 
											echo $value->category_name.':';
										?>
									</div>
									<div class="clear height-20"></div>
								<?php endif; ?>

								<div class="col-xs-4">
									<div class="item prelatif">
										<div class="pic"><img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(275,186, '/images/service/'.$value->image , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="<?php echo $value->title ?>"></div>
										<div class="clear height-20"></div>
										<div class="w220 tengah text-gothic h115">
											<div class="title"><?php echo ucwords( $value->title ); ?></div>
											<!-- <div class="clear height-15"></div> -->
											<div class="desc"><p><?php echo substr(strip_tags($value->content), 0, 45) ; ?>...</p></div>
										</div>
										<div class="bc-readmore-item text-gothic"><a href="<?php echo CHtml::normalizeUrl(array('/layanan/view', 'id'=>$value->id, 'url'=>Slug::create($value->title), 'lang'=>Yii::app()->language)); ?>">read more&nbsp;&nbsp;&nbsp; <i class="icon-mr-bt-facilities-item"></i> </a></div>
										<div class="back-shadow-item-fclities"></div>
									</div>	
								</div>
								<?php $categr = $value->category; ?>
							<?php endforeach; ?>
					</div>
				</div>

				<div class="clear height-35"></div>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
		<!-- /. End right content -->

		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
		<div class="back-bottom-fcs-grey"></div>

ticket/protected/views/layanan/index_backup.php
<?php
$this->pageTitle = $data['title'].' - '.$this->pageTitle;
?>
<div class="wfull content-full">
	<div class="container">
		<div class="content-left">
			<div class="text-content">
				<div class="height-40"></div>
				<h1 class="main-title"><?php echo $data['title'] ?></h1>
				<div class="fcs-line"></div>
				<div class="height-15"></div>
				<?php echo $data['content'] ?>
				<div class="content-list-container">
					<?php foreach ($layanan as $key => $value): ?>
					<?php
					$value['image'] = json_decode($value['image']);
					?>
					<div class="content-list">
						<div class="content-list-img">
							<a href="<?php echo CHtml::normalizeUrl(array('/layanan/view', 'id'=>$value['id'], 'url'=>Slug::create($value['name']), 'lang'=>Yii::app()->language)); ?>">
								<img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(195,232, '/images/layanan/'.$value['image']->image , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="">
							</a>
						</div>
						<div class="content-list-desc">
							<h3 class="content-list-title"><a href="<?php echo CHtml::normalizeUrl(array('/layanan/view', 'id'=>$value['id'], 'url'=>Slug::create($value['name']), 'lang'=>Yii::app()->language)); ?>"><?php echo $value['name'] ?></a></h3>
							<p><?php echo substr(strip_tags($value['content']),0,320) ?>....</p>
							<div class="link"><a href="<?php echo CHtml::normalizeUrl(array('/layanan/view', 'id'=>$value['id'], 'url'=>Slug::create($value['name']), 'lang'=>Yii::app()->language)); ?>"><i class="icon-panah"></i> <?php echo Yii::t('main', 'Read More') ?></a></div>
						</div>
					</div>
					<?php endforeach ?>
				</div>
			</div>
		</div>
		<div class="text-content menu-left-container">
			<div class="menu-left-shad-l"></div>
			<div class="menu-left-shad-r"></div>
			<div class="padding-20">
				<div class="height-35"></div>
				<h6><?php echo Yii::t('main', 'Related to this page:') ?></h6>
				<div class="menu-left-line"></div>
				<div class="height-15"></div>
				<?php $this->widget('zii.widgets.CMenu', array(
				    'items'=>$menu,
				    'encodeLabel'=>false,
				)); ?>				
				<div class="height-20"></div>
				<?php echo $this->renderPartial('//layouts/_contact') ?>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>

ticket/protected/views/layanan/view.php
<?php
	$this->pageTitle = $detail['title'].' - '.$this->pageTitle;
?>
<div class="content-inside-about prelatif">
	<div class="clear h140"></div>
	<div class="prelatif container padding-left-30">
		<div class="left breadcumb"><a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Home</a> &gt; <a href="<?php echo CHtml::normalizeUrl(array('layanan/index')); ?>">Services & Facilities</a> &gt; <b><?php echo $detail['title'] ?></b></div>
		<div class="clear height-10"></div>
		<div class="clear"></div>
	</div>
	<div class="lines-green"></div>
	<div class="prelatif container margin-left-30">
		<div class="clear height-25"></div>

		<!-- /. start left content -->
		<div class="left w257 left-content">
			<div class="inside w232">
				<?php foreach ($menu as $key => $v_Category): ?>
				<div class="t-nws-detail text-gothic"><b><?php echo ucwords($v_Category->category); ?></b></div>
				<div class="clear height-10"></div>
				<div class="menu-left-inscontent">
					<?php $menusub = Service::Model()->getMenuByCategory(1, $v_Category->service_category_id); ?>
					<!-- <ul> -->
						<?php $this->widget('zii.widgets.CMenu', array(
							    'items'=>$menusub,
							    'encodeLabel'=>false,
							)); ?>
					<!-- </ul> -->
				</div>
				<div class="clear height-20"></div>
				<?php endforeach ?>

			</div>
			<div class="clear height-40"></div>
			<div class="clear"></div>
		</div>
		<!-- /. End left content -->
		
		<!-- /. start right content -->
		<div class="left w842 right-content">
			<div class="text-content inside det-articles">
				<h1 class="title-toppages"><font style="font-weight: normal;"><?php echo ucwords($detail->title); ?></font></h1>
				<div class="clear height-20"></div>
				<div class="mg-ct-left"><img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(275,186, '/images/service/'.$detail->image , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt=""></div>
				<?php echo $detail->content ?>

				<div class="clear height-50"></div>
				<div class="t-other-arc text-gothic">Read other articles & publications:</div>
				<div class="clear height-10"></div>
				<div class="lines-green"></div>
				<div class="clear height-15"></div>

				<div class="list-item-facilities-data">
					<div class="row">
								<?php 
									$moreService = Service::model()->getServiceAll(3, $_GET['id'], 1);
								?>
								<?php $categr = ''; ?>
								<?php foreach ($moreService as $key => $value): ?>
								<?php if ($value->category != $categr): ?>
									<div class="clear"></div>
									<div class="name_kategori text-gothic">
										<?php $ncCategory = ServiceCategoryDescription::Model()->getNameByCategoryID($value->category)->category; 
											echo $ncCategory.':';
										?>
									</div>
									<div class="clear height-20"></div>
								<?php endif; ?>

								<div class="col-xs-4">
									<div class="item prelatif">
										<div class="pic"><img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(275,186, '/images/service/'.$value->image , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="<?php echo $value->title ?>"></div>
										<div class="clear height-20"></div>
										<div class="w220 tengah text-gothic h115">
											<div class="title"><?php echo ucwords( $value->title ); ?></div>
											<!-- <div class="clear height-15"></div> -->
											<div class="desc"><p><?php echo substr(strip_tags($value->content), 0, 45) ; ?>...</p></div>
										</div>
										<div class="bc-readmore-item text-gothic"><a href="<?php echo CHtml::normalizeUrl(array('/layanan/view', 'id'=>$value->id, 'url'=>Slug::create($value->title), 'lang'=>Yii::app()->language)); ?>">read more&nbsp;&nbsp;&nbsp; <i class="icon-mr-bt-facilities-item"></i> </a></div>
										<div class="back-shadow-item-fclities"></div>
									</div>	
								</div>
								<?php $categr = $value->category; ?>
							<?php endforeach; ?>
					</div>
				</div>

				<div class="clear height-35"></div>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
		<!-- /. End right content -->

		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
<div class="back-bottom-fcs-grey"></div>

ticket/protected/views/layanan/view_backup.php
<?php
$this->pageTitle = $layanan['name'].' - '.$this->pageTitle;
$layanan['image'] = json_decode($layanan['image']);
?>
<div class="wfull content-full">
	<div class="container">
		<div class="content-left">
			<div class="text-content">
				<div class="height-40"></div>
				<h1 class="main-title"><?php echo $data['title'] ?></h1>				
				<h3 style="text-align: right; margin-top: -35px; margin-bottom: 10px;"><a href="<?php echo CHtml::normalizeUrl(array('/layanan/index', 'lang'=>Yii::app()->language)); ?>"><?php echo Yii::t('main', 'Back') ?></a></h3>
				<div class="fcs-line"></div>
				<div class="height-15"></div>
				
				<?php if ($layanan['id'] != 6): ?>
					<img class="image-news" align="right" src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(250,5000, '/images/layanan/'.$layanan['image']->image , array('method' => 'resize', 'quality' => '90')) ?>" alt="">
					<h3><?php echo $layanan['name'] ?></h3>
					<?php echo $layanan['content'] ?>
				<?php else: ?>

					<h3><?php echo $layanan['name'] ?></h3>
					<?php echo $layanan['content'] ?>
					
					<div class="clear height-20"></div>
					<div class="lines"></div>
					<?php $modelListConsult = ListVisit::Model()->findAll(); ?>
					<div class="box-column-consult">
						<div class="height-20"></div>
						<div class="height-4"></div>
						<?php foreach ($modelListConsult as $key => $va_consult): ?>
						<div class="list-column-consult">
							<div class="left">
								<div class="picture"><img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(175,5000, '/images/visiting-consultan/'.$va_consult->images , array('method' => 'resize', 'quality' => '90')) ?>" alt="<?php echo $va_consult->name ?>"></div>
							</div>
							<div class="right">
								<div class="desc">
									<?php echo $va_consult->description; ?>
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear height-10"></div>
						<div class="height-3"></div>
						<?php endforeach ?>

					</div>
				<?php endif ?>

				<div class="clear"></div>
				<div class="height-15"></div>
				<div class="fcs-line"></div>
				<div class="height-15"></div>
			</div>
		</div>
		<div class="text-content menu-left-container">
			<div class="menu-left-shad-l"></div>
			<div class="menu-left-shad-r"></div>
			<div class="padding-20 padding-right-5">
				<div class="height-35"></div>
				<h6><?php echo Yii::t('main', 'Related to this page:') ?></h6>
				<div class="menu-left-line"></div>
				<div class="height-15"></div>
				<?php $this->widget('zii.widgets.CMenu', array(
				    'items'=>$menu,
				    'encodeLabel'=>false,
				)); ?>				
				<div class="height-20"></div>
				<?php echo $this->renderPartial('//layouts/_contact') ?>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>